#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function main() {
  local testFiles=$(find . -path "*/test/*" ! -path '*/test/*/*'  -name '*_test')

  if [ $# -ne 0 ]; then
    testFiles=$(grep -f <(printf '%s\n' "$@") <(cat <<<$testFiles))
  fi

  (
    readarray -t -d '' testFilesArray < <(xargs printf '%s\0' <<<"$testFiles")
    . "${SCRIPT_DIR}/testing/test-runner"
    runTests "${testFilesArray[@]}"
  )
}

main "$@"
