#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function testGradlewExec(){
  . .bin/gradlew_utils

  local result=$(assertSuccess "gradlewExec" "projects")
  log "$result"
  assertContains "$result" "BUILD SUCCESSFUL" "OUTPUT"
}

function testCurrentVersion(){
  . .bin/gradlew_utils

  local result="$(currentVersion)"
  log "$result"
  assertContains "$result" "1.2.3"
}

function testIncrementSnapshotVersion(){
  . .bin/gradlew_utils

  local version=$(increment_version "1.2.3-SNAPSHOT" 2)
  log "incremented version ${version}"
  assertEquals "1.2.4-SNAPSHOT" "$version" "increment snapshot version"
}

function testIncrementMajorVersion(){
  . .bin/gradlew_utils

  local version=$(increment_version "1.2.3" 0)
  log "incremented version ${version}"
  assertEquals "2.0.0" "$version" "increment major version"
}

function testIncrementMinorVersion(){
  . .bin/gradlew_utils

  local version=$(increment_version "1.2.3" 1)
  log "incremented version ${version}"
  assertEquals "1.3.0" "$version" "increment minor version"
}

function testIncrementPatchVersion(){
  . .bin/gradlew_utils

  local version=$(increment_version "1.2.3" 2)
  log "incremented version ${version}"
  assertEquals "1.2.4" "$version" "increment minor version"
}

function beforeEach(){
  rm -rf "$1/gradle-project"
  rm -rf "$1/gradle-remote"

  cp -rap "gradle-project" "$1"
  mv "$1/gradle-project/_git" "$1/gradle-project/.git"
  cp -rap "gradle-remote" "$1"

  cp -r "../.bin" "$1/gradle-project/.bin"

  echo "$1/gradle-project"
}