#!/usr/bin/env bash

function testResetTag(){
  prepareTestFixture

  assertSuccess git rev-parse "v1.0.1"

  ./.bin/reset_tag --batch

  assertFail git rev-parse "v1.0.1"
  assertSuccess git rev-parse "v1.0.0"

  assertContains "$(git log -n1 --oneline HEAD)" "world added."
  assertContains "$(git log -n1 --oneline HEAD~)" "hello added."
  assertContains "$(git log -n1 --oneline HEAD~2)" "new version commit:  'v1.0.1-SNAPSHOT'"
}


function prepareTestFixture(){
  prepareReleaseCommits 1.0.0
  addFileCommit hello "Hello"
  addFileCommit world "World"
  prepareReleaseCommits 1.0.1
  git push
  git push --tags
}

function prepareReleaseCommits(){
  local version="${1:-1.0.0}"
  local newVersion=$(. ./.bin/gradlew_utils; increment_version "$version" 2)
  git commit --allow-empty -m " [Gradle Release Plugin] - pre tag commit:  'v${version}'."
  git tag "v${version}"
  git commit --allow-empty -m "[Gradle Release Plugin] - new version commit:  'v${newVersion}-SNAPSHOT'."
}

function addFileCommit(){
    cat <<<$2 > $1
    git add $1
    git commit -m "$1 added."

}

function beforeEach(){
  rm -rf "$1/gradle-project"
  rm -rf "$1/gradle-remote"

  cp -rap "gradle-project" "$1"
  mv "$1/gradle-project/_git" "$1/gradle-project/.git"
  cp -rap "gradle-remote" "$1"

  cp -r "../.bin" "$1/gradle-project/.bin"

  setTestDir "$1/gradle-project"
}