#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function main() {
  (
    . "${SCRIPT_DIR}/test-runner"
    cd "$SCRIPT_DIR"
    runTests gradlew_utils_test
  )
}

main "@*"
