#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


function main() {
  beforeAll

  echo "Running gradlew_utils_test"
  ${SCRIPT_DIR}/gradlew_utils_test
}


function beforeAll(){
  if [ -d "${SCRIPT_DIR}/build/tests" ]; then
    rm -rf "${SCRIPT_DIR}/build/tests" > /dev/null
  fi

  mkdir -p "${SCRIPT_DIR}/build/tests" > /dev/null
}


main "@*"
