#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

function findGradlewPath() {
  local rootDir="$(dirname "$SCRIPT_DIR")"
  local gradleWorkdir="$(git rev-parse --show-toplevel)"
  if [ $? == 0 ]; then
      rootDir="${gradleWorkdir}"
  fi
  local gradlew_path="${rootDir}/gradlew"

  echo "${gradlew_path}"
}

function gradlewExec(){
  local gradlew="$(findGradlewPath)"

  if ! [ -f "${gradlew}" ]; then
    >&2 echo "Gradle Wrapper not found: ${gradlew}"
    exit 1
  fi

  if [ -x "${gradlew}" ]; then
    "${gradlew}" $@
    return
  fi

  >&2 echo "Gradle Wrapper is not executable: ${gradlew}"
  exit 1
}
