name: Update Subtree Branches

on:
  push:
    paths:
      - "gradle/**"
      - ".github/**"
      - "updateSubtreeBranches.sh"
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git User
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Update Subtree Branches
        env: # Or as an environment variable
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          ./updateSubtreeBranches.sh